2025-02-20 23:53:14,827 ERROR An error occurred
Traceback (most recent call last):
  File "/home/muis/thesis/github-repo/master-thesis/mc_darts.py", line 210, in main
    train(model, train_loader, optimizer, criterion)
  File "/home/muis/thesis/github-repo/master-thesis/mc_darts.py", line 171, in train
    outputs = model(images)
              ^^^^^^^^^^^^^
  File "/home/muis/miniforge3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muis/miniforge3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muis/thesis/github-repo/master-thesis/mc_darts.py", line 129, in forward
    x = cell([x, x], weights)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/muis/miniforge3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muis/miniforge3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muis/thesis/github-repo/master-thesis/mc_darts.py", line 77, in forward
    s = sum(self._ops[offset + j](h, curr_weights[j])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muis/thesis/github-repo/master-thesis/mc_darts.py", line 77, in <genexpr>
    s = sum(self._ops[offset + j](h, curr_weights[j])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muis/miniforge3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muis/miniforge3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muis/thesis/github-repo/master-thesis/mc_darts.py", line 40, in forward
    return sum(w * op(x) for w, op in zip(weights, self._ops))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muis/thesis/github-repo/master-thesis/mc_darts.py", line 40, in <genexpr>
    return sum(w * op(x) for w, op in zip(weights, self._ops))
                   ^^^^^
  File "/home/muis/miniforge3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muis/miniforge3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muis/miniforge3/lib/python3.12/site-packages/torch/nn/modules/conv.py", line 554, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muis/miniforge3/lib/python3.12/site-packages/torch/nn/modules/conv.py", line 549, in _conv_forward
    return F.conv2d(
           ^^^^^^^^^
RuntimeError: Given groups=1, weight of size [8, 8, 1, 1], expected input[64, 16, 28, 28] to have 8 channels, but got 16 channels instead
